---
title: "Quizes"
author: "Shahyar Taheri"
output: html_document
---

```{r setup, include=FALSE}
#QUIZ2
predict_word("The guy in front of me just bought a pound of bacon, a bouquet, and a case of")
predict_word("You're the reason why I smile everyday. Can you follow me please? It would mean the")
predict_word("Hey sunshine, can you follow me and make me the")
predict_word("Very early observations on the Bills game: Offense still struggling but the")
predict_word("Go on a romantic date at the")
predict_word("Well I'm pretty sure my granny has some old bagpipes in her garage I'll dust them off and be on my")
predict_word("Ohhhhh #PointBreak is on tomorrow. Love that film and haven't seen it in quite some")
predict_word("After the ice bucket challenge Louis will push his long wet hair out of his eyes with his little")
predict_word("Be grateful for the good times and keep the faith during the")
predict_word("If this isn't the cutest thing you've ever seen, then you must be")
```

```{r}
#QUIZ3
predict_word("When you breathe, I want to be the air for you. I'll be there for you, I'd live and I'd")
predict_word("Guy at my table's wife got up to go to the bathroom and I asked about dessert and he started telling me about his")
predict_word("I'd give anything to see arctic monkeys this")
predict_word("Talking to your mom has the same effect as a hug and helps reduce your")
predict_word("When you were in Holland you were like 1 inch away from me but you hadn't time to take a")
predict_word("I'd just like all of these questions answered, a presentation of evidence, and a jury to settle the")
predict_word("I can't deal with unsymetrical things. I can't even hold an uneven number of bags of groceries in each")
predict_word("Every inch of you is perfect from the bottom to the")
predict_word("I'm thankful my childhood was filled with imagination and bruises from playing")
predict_word("I like how the same people are in almost all of Adam Sandler's")
```
